### PR TITLE
🌱 Move all e2e scripts into one location

### PR DESCRIPTION
**Pull request by m1kola**
# Description

Follow up for https://github.com/operator-framework/operator-controller/pull/1003#pullrequestreview-2175049874.

Some of the e2e scripts were in `./hack` and some were in `./test/tools`. Moved everything into single location. Everything is in `./hack/test` now.

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Comment by tmshort** [comment]
I would actually suggest moving _from_ `hack` _into_ `test/tools`. `hack` to me means something [completely different](https://en.wikipedia.org/wiki/Hack_(video_game))...

**Comment by m1kola** [comment]
I moved it into hack because we use `./hack` dir in a few other repos (OLMv0, catalogd, probably more) and it was historically preceding `./test/tools`.

But I'm not opposed into getting rid of `./hack` and moving everything into `./test/tools`. I'll get back to it tomorrow.

**Comment by perdasilva** [comment]
Just my 2c (nothing blocking), seems the `hack` directory pattern is a k8s'ism (e.g. https://github.com/kubernetes/kops/issues/444) - seems many go projects copied it. While not against moving to ./test/tools, the hack dir may already be an expectation for many k8s devs in the wild. 

As an alternative, we could also move test/tools to /hack/test - and have a hack/misc for more specific purposed, non-critical-path, type scripts.

**Comment by tmshort** [comment]
I'd be ok with `hack/test`, it's at least a bit more descriptive... that being said, I _really_ hate the misuse of the term "hack" (e.g. "life hack").

**Comment by tmshort** [comment]
@m1kola ?

**Comment by m1kola** [comment]
Sorry, something more urgent came up and I was focusing on it.

Moved everything into `./hack/test`.

**Review by tmshort — APPROVED** [review]
/lgtm

**Pull request merged**
