### PR TITLE
📖 create staging folder for docs

### PR DESCRIPTION
**Pull request by anik120**
# Description

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Comment by anik120** [comment]
@joelanford @tmshort looks like I have to create an empty file in the `docs-staging` folder, git does not pick-up empty folder additions :) 

Should we just create the folder when @tmshort writes the first document for that folder?

**Comment by tmshort** [comment]
@michaelryanpeter was going to write something up...

**Comment by michaelryanpeter** [comment]
I will create the `docs-staging` when I create the PR for the version range docs.

**Comment by m1kola** [comment]
We now have `docs/drafts`. I'm going to close this PR for now. @anik120 please do not hesitate to re-open if you think it is still required.

**Pull request closed without merging**
