### PR TITLE
:book: Update GoDoc comments for the `ClusterExtension` API

### LINKED ISSUE #1143: Update GoDoc comments to be user readable
As outlined in the [Write User Readable Documentation in the GoDoc subsection of the OpenShift API Conventions](https://github.com/openshift/enhancements/blob/master/dev-guide/api-conventions.md#write-user-readable-documentation-in-godoc), each field should be sufficiently documented such that an end user can answer:
- What is the purpose of this field? What does it allow me to achieve?
- How does this field interact with other fields or features?
- What are the limitations of this field?
- Is this field optional or required?
    - IF optional, what happens if the field is omitted?

GoDoc should also follow the Go comment standards outlined in https://tip.golang.org/doc/comment

In the [RFC](https://docs.google.com/document/d/1y8Xup-4znAux76XVJVRz20NlKcejAOFfPyf6G7w8BWs/edit?usp=sharing) for #740 there is a set of proposed GoDoc changes with the intention to reduce review churn on any PRs that resolve this issue. Depending on when this change is made, the changes proposed in the RFC may need to be modified to correctly reflect the current state of the world.

### LINKED ISSUE #1144: Update GoDoc field name references to use the JSON field name
As outlined in the [Use JSON Field Names in GoDoc subsection of the OpenShift API Conventions](https://github.com/openshift/enhancements/blob/master/dev-guide/api-conventions.md#use-json-field-names-in-godoc), field names referenced in the GoDoc should use the JSON field names. 

The updates required as of writing this are:
- `Version` → `version`, [ref](https://github.com/operator-framework/operator-controller/blob/cb9ea0032c95d59d8a4951593f6486ae6c03c0bb/api/v1alpha1/clusterextension_types.go#L55-L60)
- `Channel` → `channel`, [ref](https://github.com/operator-framework/operator-controller/blob/baac660980549ef68329cd72b45906ddefa7f3c2/api/v1alpha1/clusterextension_types.go#L64-L65)
- `Preflight` → `preflight`, [ref](https://github.com/operator-framework/operator-controller/blob/cb9ea0032c95d59d8a4951593f6486ae6c03c0bb/api/v1alpha1/clusterextension_types.go#L85)
- `ServiceAccount` → `serviceAccount`, [ref](https://github.com/operator-framework/operator-controller/blob/cb9ea0032c95d59d8a4951593f6486ae6c03c0bb/api/v1alpha1/clusterextension_types.go#L87)
- `InstalledBundle` → `installedBundle`, [ref](https://github.com/operator-framework/operator-controller/blob/cb9ea0032c95d59d8a4951593f6486ae6c03c0bb/api/v1alpha1/clusterextension_types.go#L177)
- `CRDUpgradeSafety` → `crdUpgradeSafety`, [ref](https://github.com/operator-framework/operator-controller/blob/cb9ea0032c95d59d8a4951593f6486ae6c03c0bb/api/v1alpha1/clusterextension_types.go#L104)
- `Disabled` → `disabled`, [ref](https://github.com/operator-framework/operator-controller/blob/cb9ea0032c95d59d8a4951593f6486ae6c03c0bb/api/v1alpha1/clusterextension_types.go#L111)

### LINKED ISSUE #1147: Ensure optional fields have the `// +optional` tag
As outlined in the [Optional vs. Required subsection of the Kubernetes API Conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required), all optional fields should contain the `+optional` comment tag. 

The following fields need to be updated with this comment tag:
- `ClusterExtension.Spec.Version`: https://github.com/operator-framework/operator-controller/blob/baac660980549ef68329cd72b45906ddefa7f3c2/api/v1alpha1/clusterextension_types.go#L52-L60
- `ClusterExtension.Spec.Channel`: https://github.com/operator-framework/operator-controller/blob/baac660980549ef68329cd72b45906ddefa7f3c2/api/v1alpha1/clusterextension_types.go#L62-L65
- `ClusterExtension.Spec.UpgradeConstraintPolicy`: https://github.com/operator-framework/operator-controller/blob/baac660980549ef68329cd72b45906ddefa7f3c2/api/v1alpha1/clusterextension_types.go#L67-L72
- `ClusterExtension.Spec.Preflight`: https://github.com/operator-framework/operator-controller/blob/baac660980549ef68329cd72b45906ddefa7f3c2/api/v1alpha1/clusterextension_types.go#L83-L85

### PR DESCRIPTION
**Pull request by everettraven**
# Description
Updates the GoDoc comments in the `ClusterExtension` API to be more user readable, user the JSON field name in references, and ensures all optional fields are marked with the `//+optional` comment tag

- Fixes #1147 
- Fixes #1144 
- Fixes #1143 

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Comment by everettraven** [comment]
There are a couple PRs that are in the merge queue that will require a rebase for these changes. Adding a hold for now

/hold

**Comment by everettraven** [comment]
Rebased on latest merged API changes. unholding

/hold cancel

**Review by tmshort — APPROVED** [review]
/lgtm

**Review by rashmigottipati — APPROVED** [review]
/lgtm

**Pull request merged**
