### PR TITLE
Introduce CODEOWNERS

### PR DESCRIPTION
**Pull request by awgreene**
Learn more about CODEOWNERS [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#about-code-owners), or look at this description below:

> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. Code owners are not automatically requested to review draft pull requests. For more information about draft pull requests, see "[About pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests)." When you mark a draft pull request as ready for review, code owners are automatically notified. If you convert a pull request to a draft, people who are already subscribed to notifications are not automatically unsubscribed. For more information, see "[Changing the stage of a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request)."

> When someone with admin or owner permissions has enabled required reviews, they also can optionally require approval from a code owner before the author can merge a pull request in the repository. For more information, see "[About protected branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-pull-request-reviews-before-merging)."

### CODE REVIEW

**Comment by dtfranz** [comment]
I noticed the description of the `operator-framework/operator-controller-maintainers` group is "non Red Hat operator-controller-maintainers" yet it's currently populated only with Red Hat people. That isn't the case for the other projects though e.g. deppy+rukpak's equivalent groups are non Red Hat only. Any reason it's set up that way?

**Comment by tmshort** [comment]
I agree with @dtfranz that the current list seems somewhat limiting.

**Comment by tmshort** [comment]
Is there any reason not to approve this? Or do we want to update the list of OWNERS first?

**Review by perdasilva — APPROVED** [review]
lgtm

**Pull request merged**
