### PR TITLE
🐛 fix: do not silently drop finalizer updates when status is also updated

### PR DESCRIPTION
**Pull request by joelanford**
This is a fix for a bug that @anik120 stumbled upon in catalogd while working on https://github.com/operator-framework/catalogd/pull/379.

Wanted to fix it here as well while we're thinking about it.

# Description

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Comment by joelanford** [comment]
`codecov/patch` test seems to be failing because I moved the check for unexpected changes.

**Review by anik120 — DISMISSED** [review]
> `codecov/patch` test seems to be failing because I moved the check for unexpected changes.

Fwiw there were no tests added to confirm this was a problem before(which is fine coz we didn't know it was a problem), but there's no tests now to confirm on paper it is still not a problem

**Comment by tmshort** [comment]
@anik120 not sure we want to test a panic, also not sure how to get a unit test to modify fields while we're in `reconcile()` This really is a "should never happen" type of situation during normal runs. It _might_ panic if someone were making an incorrect code change.

**Review by tmshort — APPROVED** [review]
/lgtm

**Review by everettraven — APPROVED** [review]

**Pull request merged**
