### PR TITLE
✨ ADD scheme package for AddToScheme

### PR DESCRIPTION
**Pull request by acmenezes**
# Description

This PR adds a scheme package providing a central location for new apis to be added to scheme.

Also replaces the use of a new scheme instance and var by importing the package scheme and using scheme.Scheme.

Solves #322 

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Comment by acmenezes** [comment]
Hi @m1kola , I'm not sure if this is what you expected when you opened the issue #322. I'm just starting getting acquainted with the code base you have here. I didn't catch a few lines [here](https://github.com/operator-framework/operator-controller/blob/9785be89a5a91ad4c3e853d4a7ef193050650100/internal/controllers/variables_test.go#L31C1-L34C1) not sure exactly how they are being used.

**Review by perdasilva — APPROVED** [review]
lgtm

**Review by m1kola — COMMENTED** [review]
That's what I had in mind, thanks for looking into it.

It looks like imports need to be sorted and we should be good to go.

> I didn't catch a few lines [here](https://github.com/operator-framework/operator-controller/blob/9785be89a5a91ad4c3e853d4a7ef193050650100/internal/controllers/variables_test.go#L31C1-L34C1) not sure exactly how they are being used.

I think it is dead code. We can probably just remove it.

**Comment by acmenezes** [comment]
> That's what I had in mind, thanks for looking into it.
> 
> It looks like imports need to be sorted and we should be good to go.
> 
> > I didn't catch a few lines [here](https://github.com/operator-framework/operator-controller/blob/9785be89a5a91ad4c3e853d4a7ef193050650100/internal/controllers/variables_test.go#L31C1-L34C1) not sure exactly how they are being used.
> 
> I think it is dead code. We can probably just remove it.

Hi @m1kola , I remove those few lines but I saw some linting errors from a tool called gci but I couldn't determine what version you use to lint the project. Could point me to the right github repo? Then I can run it and do a clean up in order to merge the code. Thanks!

**Comment by acmenezes** [comment]
> Hi @m1kola , I remove those few lines but I saw some linting errors from a tool called gci but I couldn't determine what version you use to lint the project. Could point me to the right github repo? Then I can run it and do a clean up in order to merge the code. Thanks!

Never mind actually. I figured it out. Bingo! It's fixed now. I believe we're good to go. Thanks.

**Review by m1kola — APPROVED** [review]
Looks good. Thanks you!

> Never mind actually. I figured it out. Bingo!

Great! Take a look at `make help` - our `Makefile` has some useful commands for development. Like `make run` will spin up a Kind cluster with all the required components installed + will compile operator-controller from local source code and deploy it as well.

If you have any questions about development process - don't hesitate to ask on issues/PR or on Kubernetes slack ([channel `#olm-dev`](https://kubernetes.slack.com/archives/C0181L6JYQ2)).

**Comment by m1kola** [comment]
Trying to merge again. I think I introduced a flake in https://github.com/operator-framework/operator-controller/pull/785 and that's why e2e failed in merge queue.

**Pull request merged**
