### PR TITLE
:sparkles: Move helm-operator-plugin

### PR DESCRIPTION
**Pull request by tmshort**
# Description

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Comment by tmshort** [comment]
@varshaprasad96 @joelanford This is _one_ thing I missed in the original rukpak. The `depedent.go` file can also be found here:
https://github.com/operator-framework/rukpak/blob/main/internal/helm-operator-plugins/predicate/depedent.go
 This does mean exposing more in rukpak

**Comment by joelanford** [comment]
Let's change rukpak. Also, instead of `reflect` we should use this instead: https://github.com/kubernetes/apimachinery/blob/37988e577e160bf7749437141fee1d6b8ca15dd6/pkg/api/equality/semantic.go#L28

**Comment by tmshort** [comment]
@joelanford, I updated rukpak: https://github.com/operator-framework/rukpak/pull/878
But I would consider the reflect changes separate.

**Review by varshaprasad96 — APPROVED** [review]
/lgtm
/approve

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Pull request merged**
