### PR TITLE
Clean-up of operator conditions with helper funcs

### PR DESCRIPTION
**Pull request by jmprusi**
# Description

Clean-up of operator conditions with helper funcs.

Requires https://github.com/operator-framework/operator-controller/pull/218
follow-up of https://github.com/operator-framework/operator-controller/pull/218#discussion_r1200754022

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Comment by tmshort** [comment]
Needs a rebase after merging #218.

**Comment by jmprusi** [comment]
> Needs a rebase after merging #218.

fixed!

**Review by everettraven — APPROVED** [review]
/lgtm

**Review by tmshort — APPROVED** [review]

**Comment by jmprusi** [comment]
@tmshort thanks! Can you please attach this one to the OLM v1 and v0.2.0 milestone? I can't do it myself.

**Comment by tmshort** [comment]
This is not an issue...

**Comment by tmshort** [comment]
@everettraven right, I can set the label, but it won't show it automatically.

**Comment by tmshort** [comment]
(It would also help if I look just under the labels... D'Oh)

**Pull request merged**
