### PR TITLE
🌱 add Github action to capture logs and pod descriptions when e2e fails

### PR DESCRIPTION
**Pull request by camilamacedo86**
# Description

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Comment by everettraven** [comment]
Just a note that our e2e action should already have logic to upload artifacts upon failure. For example, https://github.com/operator-framework/operator-controller/actions/runs/11746095340

The artifacts are gathered by https://github.com/operator-framework/operator-controller/blob/e51c0c205ec09e51691579cacbedc3ac53e4bd54/test/e2e/cluster_extension_install_test.go#L865-L991 on test failure

**Comment by camilamacedo86** [comment]
Hi @everettraven 

> Just a note that our e2e action should already have logic to upload artifacts upon failure. For example, https://github.com/operator-framework/operator-controller/actions/runs/11746095340

I see that, but IHMO it is not so straightforward way helpful as looking the logs in the action. I do not see any harm to add it but if you folks see any reason for not please let me know.

**Comment by joelanford** [comment]
IMO, we should not have two different ways of doing this. If we can improve on what's there, great! If we need to replace what we already have with an alternate method, let's make sure we pull in the folks that were involved with the original implementation to make sure there we account for everything that was originally considered. For example, was there some specific reason that we did _NOT_ use a log-based approach?

**Comment by camilamacedo86** [comment]
Fair enough.
Closing this one as not accepted.

**Pull request closed without merging**
