### PR TITLE
🐛 Demonstrate that admission cannot ensure field uniqueness.

### PR DESCRIPTION
**Pull request by benluddy**
# Description

The only field you can practically guarantee uniqueness on is .metadata.name because it is used to construct the etcd key, and etcd does offer consistency. API servers can't because they can handle more than one concurrent request for the same resource and both can be past admission but before storage. There's also latency between creation and an update to the binding's param informer. The problems gets worse in HA setups when you have multiple kube-apiserver instances.

This test nearly always fails on my machine against a kind cluster set up with `make run`:

```
    cluster_extension_admission_test.go:164: duplicate package name: pkg-x (47 duplicates)
--- FAIL: TestClusterExtensionPackageUniquenessConsistency (0.13s)
```

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@joelanford @m1kola FYI

**Comment by benluddy** [comment]
https://github.com/operator-framework/operator-controller/actions/runs/8927081787/job/24519632591?pr=819#step:4:393

```
 === RUN   TestClusterExtensionPackageUniquenessConsistency
    cluster_extension_admission_test.go:163: duplicate package name: pkg-x (18 duplicates)
--- FAIL: TestClusterExtensionPackageUniquenessConsistency (0.13s)
```

**Comment by joelanford** [comment]
Thanks! And also, 😭.

As our resident apiserver experts, do you have any suggestions about how to handle package uniqueness. Should we keep these best effort admission checks and then fallback to a reconciler-based check? Even then, it seems like we'd need to have some synchorization going on to avoid similar problems detecting dups in a reconciler.

**Comment by benluddy** [comment]
If you must guarantee that at most one ClusterExtension resource can have a certain package name, the only practical option is to validate that ClusterExtension's metadata.name is the same as spec.packageName. If you do that, duplicate name conflicts come from the etcd level and will be consistent.

The prior art on this that comes to mind is name validation for CustomResourceDefinitions and the singleton pattern (validating that metadata.name matches some constant string).

**Comment by joelanford** [comment]
I think that's what OCP platform-operators does. I need to see if all package names validate as `metadata.name` though.

**Comment by m1kola** [comment]
Thanks for the demo and explanation. At some point I was wondering about issues of this sort. My bad for not digging deeper.

**Comment by varshaprasad96** [comment]
Please hold this from merging till https://github.com/operator-framework/operator-controller/pull/846 gets in. Thanks!

**Pull request closed without merging**
