### PR TITLE
(doc-site) Remove PRD from doc site

### PR DESCRIPTION
**Pull request by anik120**
Also order docs in the Tasks folder using 'nav' in mkdocs.yml

# Description

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by ncdc** [comment]
Going to merge and do some follow ups

**Pull request merged**
